### ISSUE TITLE
WFC using SSL

### ISSUE THREAD

**Issue by cyoann** [brainfoolong/web-ftp-client#16]
Hi,

I would like to use SSL with WFC but this causes mixed content because of the web socket as you can see here.
![mixedcontent](https://user-images.githubusercontent.com/38630523/47145489-2de4db80-d2ca-11e8-8d2c-9a80ca17eaad.PNG)

So i've tried to change ws:// to wss:// in socket.js:10 but this makes the page does not load and puts a message "Reloading the page in 5 seconds".

Is there anything else to change to make it work?

Thanks in advance!

**Comment by brainfoolong** [comment]
Enabling SSL is a pretty complicated task because you need valid certs. On one of my other projects using websockets someone tried this to get it working and it worked, but it's not easy to configure. I don't have a step by step guide, sorry. Maybe this link will help you

https://github.com/brainfoolong/rcon-web-admin/issues/9

**Comment by cyoann** [comment]
I will take a look at your link, thank-you for your prompt response!
